// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TP_Parcial;

namespace TP_Parcial.Migrations
{
    [DbContext(typeof(TareasDbcontext))]
    [Migration("20201008025841_version 2")]
    partial class version2
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.8");

            modelBuilder.Entity("TP_Parcial.Detalles", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("fecha")
                        .HasColumnType("DateTime");

                    b.Property<int>("recursosId")
                        .HasColumnType("int");

                    b.Property<int>("tareasId")
                        .HasColumnType("int");

                    b.Property<int>("tiempo")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("recursosId");

                    b.HasIndex("tareasId");

                    b.ToTable("Detalles");
                });

            modelBuilder.Entity("TP_Parcial.Recursos", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasMaxLength(100);

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("varchar(100)")
                        .HasMaxLength(100);

                    b.Property<int>("UsuariosId")
                        .HasColumnType("int")
                        .HasMaxLength(100);

                    b.HasKey("id");

                    b.HasIndex("UsuariosId");

                    b.ToTable("Recursos");
                });

            modelBuilder.Entity("TP_Parcial.Tareas", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("estado")
                        .IsRequired()
                        .HasColumnType("varchar(100)")
                        .HasMaxLength(100);

                    b.Property<int>("estimacion")
                        .HasColumnType("int")
                        .HasMaxLength(100);

                    b.Property<int>("recursosId")
                        .HasColumnType("int")
                        .HasMaxLength(100);

                    b.Property<string>("titulo")
                        .IsRequired()
                        .HasColumnType("varchar(100)")
                        .HasMaxLength(100);

                    b.Property<DateTime>("vencimiento")
                        .HasColumnType("DateTime")
                        .HasMaxLength(50);

                    b.HasKey("id");

                    b.HasIndex("recursosId");

                    b.ToTable("Tareas");
                });

            modelBuilder.Entity("TP_Parcial.Usuarios", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Clave")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasMaxLength(20);

                    b.Property<string>("Usuario")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasMaxLength(50);

                    b.HasKey("id");

                    b.ToTable("Usuario");
                });

            modelBuilder.Entity("TP_Parcial.Detalles", b =>
                {
                    b.HasOne("TP_Parcial.Recursos", "recurso")
                        .WithMany()
                        .HasForeignKey("recursosId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TP_Parcial.Tareas", "tarea")
                        .WithMany()
                        .HasForeignKey("tareasId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TP_Parcial.Recursos", b =>
                {
                    b.HasOne("TP_Parcial.Usuarios", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuariosId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TP_Parcial.Tareas", b =>
                {
                    b.HasOne("TP_Parcial.Recursos", "responsable")
                        .WithMany()
                        .HasForeignKey("recursosId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
